# Numpy Math Operation


In [3]:
import numpy as np

Arithmatic Operation

In [4]:
arr1 = np.arange(9, dtype='i').reshape(3,3)
arr2 = np.arange(10,19, dtype='i').reshape(3,3)

print(arr1)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [5]:
print(np.add(arr1,arr2))

[[10 12 14]
 [16 18 20]
 [22 24 26]]


In [6]:
print(np.subtract(arr2,arr1))

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [7]:
print(np.multiply(arr1,arr2))

[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]


In [8]:
print(np.divide(arr2,arr1))
print(np.divide(arr1,arr2))

[[        inf 11.          6.        ]
 [ 4.33333333  3.5         3.        ]
 [ 2.66666667  2.42857143  2.25      ]]
[[0.         0.09090909 0.16666667]
 [0.23076923 0.28571429 0.33333333]
 [0.375      0.41176471 0.44444444]]


C:\Users\indra\AppData\Local\Temp\ipykernel_952\318583799.py:1: RuntimeWarning: divide by zero encountered in divide
  print(np.divide(arr2,arr1))


numpy.reciprocal()

ar=np.array([4,9,8,9,8,85,1,8,7]).reshape(3,3)
print(np.reciprocal(ar))

In [10]:
ar = np.array([12, 13.7, 14, 15.2, 16, 17.6, 18.9, 19.5, 20]).reshape(3, 3)
print(np.reciprocal(ar))

[[0.08333333 0.0729927  0.07142857]
 [0.06578947 0.0625     0.05681818]
 [0.05291005 0.05128205 0.05      ]]


numpy.power():

In [14]:
ar=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(np.power(ar,2))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


numpy.mod():

In [17]:
ar1=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
ar2=np.array([2,4,6,8,10,12,14,16,18]).reshape(3,3)
print(np.mod(ar2,ar1))
print(np.mod(ar1,ar2))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.dot():

In [18]:
print(np.dot(10, 12))

120


In [20]:
ar1=np.array([12])
ar2=np.array([4])
print(np.dot(ar1,ar2))

48


# Using Numpy Arrays with Conditional Expressions

In [22]:
import numpy as np

arr = np.array([12,15,86,75,475,44,474,454,75,7])

for i in arr:
    if i % 2 == 0:
        print(i, "is even")
    else:
        print(i, "is odd")

12 is even
15 is odd
86 is even
75 is odd
475 is odd
44 is even
474 is even
454 is even
75 is odd
7 is odd


In [23]:
arr1 = np.array([[True, False], [True, True]])
arr2 = np.array([[False, False], [False, True]])

print(np.logical_or(arr1, arr2))
print(np.logical_and(arr1, arr2))

[[ True False]
 [ True  True]]
[[False False]
 [False  True]]


# Aggregation Functions in NumPy

sum:- Python numpy sum function calculates the sum of values in an array.

In [28]:
arr= np.array(10)
print(np.sum(arr))
print(arr.sum())

arr2=np.array([20])
print(np.sum(arr2))
print(arr2.sum())

arr3=np.array([23,48,586,7858])
print(np.sum(arr3))
print(arr3.sum())

10
10
20
20
8515
8515


In [30]:
arr = np.arange(1, 10, dtype='i').reshape(3, 3)

print(arr.sum(axis = 0))
print(arr.sum(axis = 1))


[12 15 18]
[ 6 15 24]
