# Numpy Array Create

In [3]:
import numpy as np
print(np.__version__)
arr = np.array([4,5,8,5,2,7,5,5])
arr

2.3.2


array([4, 5, 8, 5, 2, 7, 5, 5])

In [34]:
print(arr.size)

8


In [35]:
print(arr.ndim)
print(arr.dtype)
print(arr.itemsize)

1
int64
8


2-D Array

In [5]:
arr=np.array([[1,5,5],[8,6,8]])
arr

array([[1, 5, 5],
       [8, 6, 8]])

3-D Array

In [6]:
arr=np.array([[[4,6,8],[1,5,32],[47,25,5]]])
arr

array([[[ 4,  6,  8],
        [ 1,  5, 32],
        [47, 25,  5]]])

Array Reshape

In [8]:
a=np.array([4,7,4,47,7,47,1,78,17])
arr=a.reshape(3,3)
arr

array([[ 4,  7,  4],
       [47,  7, 47],
       [ 1, 78, 17]])

Flattening in array :-  converting a multidimensional array into a 1D array.

In [11]:
a=np.array([[4,82,8],[5,5,74]])
arr=a.reshape(-1)
arr

array([ 4, 82,  8,  5,  5, 74])

# Attribute of ndarray

1. ndmin: ndim attribute returns an integer that tells us how many dimensions the array have.

In [16]:
a=np.array([4,32,7,2,128,27,845,788,75,7])
b=np.array([[4,82,8],[4,8,4]])
print(a.ndim)
print(b.ndim)

1
2


2.Shape

In [18]:
a=np.array([4,32,7,2,128,27,845,788,75,7])
x=np.array(45)
b=np.array([[4,82,8],[4,8,4]])
print(a.shape)
print(b.shape)
print(x.shape)

(10,)
(2, 3)
()


3. Size:- Return total number of element

In [19]:
a=np.array([4,32,7,2,128,27,845,788,75,7])
x=np.array(45)
b=np.array([[4,82,8],[4,8,4]])
print(a.size)
print(b.size)
print(x.size)

10
6
1


# Array Indexing

1-D array :- The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [24]:
arr=np.array([4,82,8,5,72,8])
print(arr[2])

8


2-D Array :- To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

In [28]:
arr=np.array([[4,7,5],[4,47,86]])
print(arr[1,2])

86


3-D Array :- To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.


In [32]:
arr=np.array([[[4,7,5],[6,54,545]],[[4,47,86],[5,85,75]]])
print(arr[0,1,0])

6


# Array Slicing

In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]


Slicing 2-D Arrays: Slices or indices are separated by comma.

In [35]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:3])

[7 8 9]
[3 8]
[[2 3]
 [7 8]]


# Array Creation Using Numpy Function 

1. zeros: Create array with all elements 0, with given dimensions.

In [37]:
a = np.zeros((4,4), dtype=int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


2. ones: Create array with all elements 1, with given dimensions.

In [39]:
a = np.ones((7,4), dtype=int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


3. arange() Function: Create a sequence of number using arange() function.

In [40]:
a = np.arange(10)
print(a)

b = np.arange(11,22,dtype='f')
print(b)

[0 1 2 3 4 5 6 7 8 9]
[11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21.]


4. eye: Return an 2-D array with 1's at diagonals and 0 elsewhere.

In [43]:
e = np.eye(4)
t = np.eye(4,5)
print(e)
print(t)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


5. identity: Same as eye(), but take only one argument. So, row=col.

In [42]:
s = np.identity(5, dtype='i')
print(s)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
